# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
git:
  autoFetch: false
  autoRefresh: false
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --line-numbers
gui:
  showCommandLog: false
  #--line-numbers --features=colibri --syntax-theme base16-256 -s
quitOnTopLevelReturn: false
disableStartupPopups: true

